BROOKLYN-4381 : Add support for AT+ORP interface
SierraWireless/octave-orp pull request #10
Opened 2021-09-27 09:37 UTC by gbetous-swir

2021-09-27 10:05 UTC, Nico26-sw requested changes
Hi Guillaume, I have some remarks and questions
Thanks

2021-09-27 10:05 UTC, Nico26-sw commented on clients/c/src/orpClient.c
> + * Deframe and decode AT packets
Not sure this function really decodes AT packets :smile: 
`orp_AtDumpFrame` ?

2021-09-27 10:42 UTC, fdur reviewed
Minor comment
I'll check deeply later

2021-09-28 14:07 UTC, imorrisonca requested changes
Hi @gbetous-swir 

The changes look quite good.  I just had some minor comments around formatting.

Thanks,
Ian

2021-09-28 14:07 UTC, imorrisonca commented on clients/c/src/at.c
> +        dest[dst_idx++]=src[src_idx];
Yes, please use white space between operators such as `=`, `+`, etc.

2021-09-29 08:12 UTC, gbetous-swir commented on clients/c/src/at.c
> +static char* AT_SUFFIX="\"\n";
I renamed at_suffix and at_prefix to copy style on hdlc.c (e.g. crc_tabccitt_init )

2021-09-29 12:08 UTC, Nico26-sw approved these changes
Look good to me, thanks !

2021-09-29 14:17 UTC, imorrisonca approved these changes
Looks good - thanks

2021-10-01 11:03 UTC, merged